# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: How to code - The best coding website for beginners.
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  How to code is the best website for beginners. With step-by-step guides and customer advice forums, you can't go wrong.
baseurl: "/info" # the subpath of your site, e.g. /blog
url: "http://www.how-to-code.net" # the base hostname & protocol for your site
twitter_username: 
github_username:  ostephagus

# Build settings
markdown: kramdown
